export const INCREMENT_ENTHUSISASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSISASM;

export const DECREMENT_ENTHUSISASM = 'DECREMENT_ENTHUSISASM';
export type DECREMENT_ENTHUSISASM = typeof DECREMENT_ENTHUSISASM;